# Generated by Django 3.2.5 on 2021-07-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210710_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_texti',
            new_name='question_text',
        ),
    ]
